### ISSUE TITLE
please update docs to include an example that shows how to pass through a redirect_uri.

### ISSUE THREAD

**Issue by markstos** [buehler/node-passport-zitadel#196]
Thanks!

**Comment by buehler** [comment]
Hey @markstos :)

Since this only supports OAUTH introspection up until now, there is no possibility for `redirect_uri`. You'll need to have some OIDC application that does the auth flow and fetches the bearer token for you first. This ZITADEL strategy only validates an existing token with the ZITADEL API.

**Comment by buehler** [comment]
Just found something as additional info: https://www.passportjs.org/packages/passport-openidconnect/ something like this could be used ;-)

**Comment by markstos** [comment]
Thanks. It could be helpful to update the README to explalin that you might want to use passport-openidconnect in addition to or instead of this module. I presumed this module would be the primary way to connect with Zitadel using OIDC, but maybe that's wrong and it has a more specialized use.
